---
driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-16.04
    driver:
      box: express42/ubuntu-16.04

suites:
  - name: pgbarman
    run_list:
      - recipe[apt]
      - recipe[bartender::test_server]
      - recipe[bartender::test_ssh_access]
