---
driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-14.04
    driver:
      box: express42/ubuntu-14.04
      memory: 4096
  - name: debian-7.6

suites:
  - name: pgbarman
    run_list:
      - recipe[apt]
      - recipe[bartender::testserver]
