language: ruby
cache: bundler
sudo: false
rvm:
- 2.1.5
bundler_args: "--without kitchen_vagrant"
before_install:
- openssl aes-256-cbc -K $encrypted_a5285f517a90_key -iv $encrypted_a5285f517a90_iv
   -in ./travis/secret_keys.tar.enc -out .travis/secret_keys.tar -d
- tar xf .travis/secret_keys.tar -C .travis
- mv .travis/travis ~/.ssh/id_rsa
script:
- bundle exec rubocop
- bundle exec foodcritic -f any .
- bundle exec kitchen test -c 10 -d always
deploy:
  edge: true
  provider: chef-supermarket
  user_id: express42
  client_key: ".travis/express42.pem"
  cookbook_category: Databases
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
